USE [MMV_SAP_DMS_DRAW]
GO

/****** Object:  Table [dbo].[M_VNCUSTOMERMASTER]    Script Date: 8/30/2019 5:54:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[M_VNCUSTOMERMASTER](
	[CUSTOMER_CD] [bigint] IDENTITY(1,1) NOT NULL,
	[CUSTOMER_CODE] [nvarchar](50) NULL,
	[DISTRIBUTOR_CODE] [nvarchar](50) NULL,
	[CUSTOMER_NAME_1] [nvarchar](512) NULL,
	[CUSTOMER_NAME_2] [nvarchar](512) NULL,
	[CUSTOMER_ADDRESS] [nvarchar](max) NULL,
	[CUSTOMER_ADDRESS_2] [nvarchar](max) NULL,
	[CUSTOMER_ADDRESS_3] [nvarchar](max) NULL,
	[CUSTOMER_ADDRESS_4] [nvarchar](max) NULL,
	[CITY] [nvarchar](255) NULL,
	[SAP_DMS_ROUTE] [nvarchar](50) NULL,
	[MOBILE_PHONE] [nvarchar](50) NULL,
	[IDMS_CUSTOMER_NO] [nvarchar](50) NULL,
	[GLOBAL_RE] [varchar](50) NULL,
	[CUSTOMER_CHAIN_CODE] [nvarchar](50) NULL,
	[INDIA_SUB_RE] [nvarchar](50) NULL,
	[SALES_CODE] [nvarchar](50) NULL,
	[SALES_DISTRICT] [nvarchar](50) NULL,
	[SALES_REGION] [nvarchar](50) NULL,
	[REGION] [nvarchar](50) NULL,
	[LATITIDE] [float] NULL,
	[LONGTITIDE] [float] NULL,
	[CREATEDATE] [nvarchar](50) NULL,
	[CREATE_BY] [nvarchar](50) NULL,
	[ACTIVE] [bit] NULL,
	[CREATED_DATE] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[M_VNCUSTOMERMASTER] ADD  CONSTRAINT [DF_M_VNCUSTOMERMASTER_ACTIVE_180805]  DEFAULT ((1)) FOR [ACTIVE]
GO

ALTER TABLE [dbo].[M_VNCUSTOMERMASTER] ADD  CONSTRAINT [DF_M_VNCUSTOMERMASTER_CREATED_DATE_180805]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO


