USE [MMV_SAP_DMS_DRAW]
GO

/****** Object:  Table [dbo].[H_FILE_UPLOAD]    Script Date: 8/30/2019 5:54:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[H_FILE_UPLOAD](
	[FILE_UPLOAD_CD] [bigint] IDENTITY(1,1) NOT NULL,
	[FILE_UPLOAD_NAME] [nvarchar](max) NULL,
	[FILE_UPLOAD_STATTUS] [bit] NULL,
	[FEATURE] [nvarchar](max) NULL,
	[USER_UPLOAD] [nvarchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[ERROR] [nvarchar](max) NULL,
 CONSTRAINT [PK_FILE_UPLOAD] PRIMARY KEY CLUSTERED 
(
	[FILE_UPLOAD_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[H_FILE_UPLOAD] ADD  CONSTRAINT [DF_FILE_UPLOAD_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO


