//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMV.MasterData {
    
    public partial class SalesRoute {
        protected System.Web.UI.HtmlControls.HtmlForm frmMain;
        protected AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManagerMain;
        protected System.Web.UI.UpdatePanel P5sUpanelSearch;
        protected System.Web.UI.WebControls.TextBox P5sFilterTxt;
        protected System.Web.UI.WebControls.Panel P5sFilterPanel;
        protected System.Web.UI.WebControls.LinkButton P5sSearch;
        protected System.Web.UI.WebControls.LinkButton P5sLbtnNew;
        protected System.Web.UI.UpdatePanel P5sUpanelDetailMain;
        protected System.Web.UI.WebControls.Panel P5sPanelDetailMain;
        protected System.Web.UI.WebControls.Label P5sLblSALES_CODE;
        protected System.Web.UI.WebControls.Label P5sLblSALES_NAME;
        protected System.Web.UI.WebControls.Label P5sLblDISTRIBUTOR_DESC;
        protected System.Web.UI.UpdatePanel P5sUpanelAddRoute;
        protected System.Web.UI.WebControls.TextBox P5sTxtROUTE_CD;
        protected System.Web.UI.WebControls.LinkButton P5sLbtnInsert;
        protected System.Web.UI.WebControls.LinkButton P5sLbtnCancel;
        protected System.Web.UI.UpdatePanel P5sUpanelMainGV;
        protected System.Web.UI.WebControls.Label P5sLblEmptyRow;
        protected System.Web.UI.WebControls.Panel P5sPanelMainGV;
        protected System.Web.UI.WebControls.DropDownList P5sDdlMainPaging;
        protected System.Web.UI.WebControls.LinkButton W5sLbtnRemoveRoute;
        protected System.Web.UI.WebControls.LinkButton P5sLbtnMoveRoute;
        protected System.Web.UI.WebControls.GridView P5sMainGridView;
        protected System.Web.UI.WebControls.HiddenField P5sHdfPopup;
        protected System.Web.UI.WebControls.Panel P5sPnlTabControl;
        protected System.Web.UI.WebControls.Panel Panel2;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.ImageButton P5sImgCanncelConfirmPopup;
        protected System.Web.UI.WebControls.TextBox P5sTxtSELECT_NEW_SALE;
        protected System.Web.UI.WebControls.LinkButton P5sLbtnConfirmMoveRoute;
        protected AjaxControlToolkit.ModalPopupExtender ModalPopupExtender;
    }
}
