namespace MMV
{
    using System.Collections.Generic;


    public partial class L5sMaster : System.Web.UI.MasterPage
    {

        public static Dictionary<string, string> L5sLangs = new Dictionary<string, string>()
            {
            #region Languages of menu
                {"Trade Activities","Trade Activities"},
                {"Define Program","Define Program"},
                {"DSR Photos Audit","DSR Photos Audit"},
                {"CDS Photos Audit","CDS Photos Audit"},
                {"Games ","Games "},
                {"Define a game","Define a game"},
                {"Restore Cancelled Prizes","Restore Cancelled Prizes"},
                {"Validating Prize","Validating Prize"},
                {"Blocked Customer List","Blocked Customer List"},

                {"Define a 5P","Define a 5P"},
                {"POC","POC"},
                {"Define a POC program","Define a POC program"},
                {"Survey","Survey"},
                {"Define a Survey","Define a Survey"},
                {"Dashboard","Dashboard"},
                {"Upload MTD Primary","Upload MTD Primary"},
                {"Upload MTD Secondary","Upload MTD Secondary"},
                {"Upload YTD Primary","Upload YTD Primary"},
                {"Upload YTD Secondary","Upload YTD Secondary"},
                {"Reports","Reports"},
                {"Stores list","Stores list"},
                {"New Stores added by DSRs","New Stores added by DSRs"},
                {"Sales Performance","Sales Performance"},
                {"eLucky","eLucky"},
                {"MMV","MMV"},
                {"Tracking","Tracking"},
                {"POC Tracking","POC Tracking"},
                {"Admin","Admin"},
                {"Master","Master"},
                {"Tool","Tool"},
                {"DSR Performance","DSR Performance"},
                {"Required Stock","Required Stock"},
                {"Unvisited Customers","Unvisited Customers"},
                {"No Sales Customers","No Sales Customers"},
                {"Required Min Stock","Required Min Stock"},
                {"Secondary Std Report","Secondary Std Report"},
                {"Prize allocation and spending","Prize allocation and spending"},
                {"Allocation and recall prize","Allocation and recall prize"},
                {"Prize by Customers (Accumulate)","Prize by Customers (Accumulate)"},
                {"Prize by customer by Date","Prize by customer by Date"},
                {"FPIT Vs DMS Data Tracking","FPIT Vs DMS Data Tracking"},
                {"Blocked customers list","Blocked customers list"},
                {"Total Prize Spending by DSR","Total Prize Spending by DSR"},
                {"AD Admin","AD Admin"},
                {"AD Commune Coverage By District","AD Commune Coverage By District"},
                {"AD Coverage By Area","AD Coverage By Area"},
                {"AD Coverage By District","AD Coverage By District"},
                {"AD Coverage By Province","AD Coverage By Province"},
                {"AD Coverage By Ward","AD Coverage By Ward"},
                {"AD POIs","AD POIs"},
                {"AD Sales Vs Population By Commune","AD Sales Vs Population By Commune"},
                {"AD Sales Vs Population By District","AD Sales Vs Population By District"},
                {"AD Sales Vs Population By Province","AD Sales Vs Population By Province"},
                {"AD Store Coverage By Commune","AD Store Coverage By Commune"},
                {"AD Store Coverage By District","AD Store Coverage By District"},
                {"AD Store Coverage By Province","AD Store Coverage By Province"},
                {"CP Admin","CP Admin"},
                {"AD Commune Coverage by Area","AD Commune Coverage by Area"},
                {"AD Commune Coverage by Distributor","AD Commune Coverage by Distributor"},
                {"CP Coverage by Area","CP Coverage by Area"},
                {"CP Coverage by Region","CP Coverage by Region"},
                {"CP POIs","CP POIs"},
                {"CP Store Coverage By Area","CP Store Coverage By Area"},
                {"CP Store Coverage By Distributor","CP Store Coverage By Distributor"},
                {"Customers Coverage Progress","Customers Coverage Progress"},
                {"Geography Coverage Progress","Geography Coverage Progress"},
                {"Summary Mapping by Area","Summary Mapping by Area"},
                {"Summary Mapping by Distributor","Summary Mapping by Distributor"},
                {"Summary Mapping by DSR","Summary Mapping by DSR"},
                {"Summary Mapping by Route","Summary Mapping by Route"},
                {"Tracking Gross Sales And Order Number","Tracking Gross Sales And Order Number"},
                {"Daily Route Visit Compliance","Daily Route Visit Compliance"},
                {"Stores with Geocode change","Stores with Geocode change"},
                {"Stop points tracking details by DSR by Date","Stop points tracking details by DSR by Date"},
                {"No of stores visited by DSR by date","No of stores visited by DSR by date"},
                {"No of Stops by DSR by Date","No of Stops by DSR by Date"},
                {"Distributor KPI Tracking","Distributor KPI Tracking"},
                {"DSRs KPI Tracking","DSRs KPI Tracking"},
                {"Stores Modification","Stores Modification"},
                {"DSRs KPI & Sales Tracking","DSRs KPI & Sales Tracking"},
                {"Customers monthly visit","Customers monthly visit"},
                {"Tracking Actual Physical Visit Vs Number Of Stops","Tracking Actual Physical Visit Vs Number Of Stops"},
                {"Geocode Checking","Geocode Checking"},
                {"DSR Store Photo","DSR Store Photo"},
                {"CDS Store Photo","CDS Store Photo"},
                {"Tracking Actual Physical Time Visit","Tracking Actual Physical Time Visit"},
                {"Distribution","Distribution"},
                {"Share of Shelf","Share of Shelf"},
                {"Monitor Login History","Monitor Login History"},
                {"Importing History","Importing History"},
                {"Upload Picture/Video","Upload Picture/Video"},
                {"DRS List","DRS List"},
                {"Supervisor List","CMD List"},
                {"Monthly Customer Visit","Monthly Customer Visit"},
                {"Summary","Summary"},
                {"Master Data ","Master Data "},
                {"Team Leader Master","Team Leader Master"},
                {"Group Leader Master","Group Leader Master"},
                {"Region Master","Region Master"},
                {"Area Master","Area Master"},
                {"Distributors Master","Distributors Master"},
                {"CDM Master","CDM Master"},
                {"Add new stores on MMV","Add new stores on MMV"},
                {"Daily Route for DSR","Daily Route for DSR"},
                {"DSRs Master","DSRs Master"},
                {"Making working route for CDS","Making working route for CDS"},
                {"Making working route for ASM","Making working route for ASM"},
                {"Product Hierarchy","Product Hierarchy"},
                {"Imports","Imports"},
                {"Auto Mapping (From Geocode -> Communes)","Auto Mapping (From Geocode -> Communes)"},
                {"Dynamic Report","Dynamic Report"},

                {"Monthly Target for DSRs","Monthly Target for DSRs"},
                {"Daily Sales Importing","Daily Sales Importing"},
                {"Gross Sales From DMS","Gross Sales From DMS"},
                {"Prize From DMS","Prize From DMS"},
                {"MTD KPI","MTD KPI"},
                {"Required stock level by stores","Required stock level by stores"},
                {"Secondary Sales","Secondary Sales"},
                {"MSS Group ","MSS Group "},
                {"Administration","Administration"},
                {"No of Routes to download","No of Routes to download"},
                {"Messaging","Messaging"},
                {"User","User"},
                {"Role","Role"},
                {"Geo Modification Unlock","Geo Modification Unlock"},
                {"Unmap Customer from Country Hier","Unmap Customer from Country Hier"},
                {"System Access Log","System Access Log"},
                {"Coverage","Coverage"},
                {"Coverage by Sales","Coverage by Sales"},
                {"Route Planning","Route Planning"},
                {"Distributor Network","Distributor Network"},
                {"Load Distributor","Load Distributor"},
                {"Data Mapping","Data Mapping"},



                {"Quick Board   ","Quick Board   "},
                {"FF Working Locations","FF Working Locations"},
                {"Stores Coverage","Stores Coverage"},
                {"Commune Coverage","Commune Coverage"},
                {"Display Management","Display Management"},
                {"Home","Home"},
                {"YTD Secondary","YTD Secondary"},
                {"YTD Primary","YTD Primary"},
                {"MTD Secondary","MTD Secondary"},
                {"MTD Primary","MTD Primary"},
                {"My Map","My Map"},
                {"Field Force Productivity Improving Tool (FPIT)","Field Force Productivity Improving Tool (FPIT)"},

                {"Master Data","Master Data"},
                {"Report","Report"},
                {"Import","Import"},

                {"Retail Enviroment","Retail Enviroment"},

                {"Summary MSS for CDM or HQ","Summary MSS for CDM or HQ"},
                {"MSS Sales","MSS Sales"},
                {"MSS Distributor","MSS Distributor"},
                {"MSS IMport","MSS IMport"},
                

            #endregion


            #region Languages of form and report

            //Trang login
               {"Title", "Welcome to Map My Country"},
                {"Login", "Login"},
                {"ID", "ID"},
                {"Password", "Password"},
                {"Welcome to Map My Country", "Welcome to Map My Country"},
                //Các nút cần tạo khi làm 1 form nhập
                {"Save","Save" },
                {"Update","Update" },
                {"Cancel","Cancel" },
                {"Confirm","Confirm" },
                {"Search", "Search"},
                {"Add New","Add New" },
                {"Reset","Reset" },
                {"Add","Add" },
                {"Back","Back" },

                //Các câu thông báo của form
                {"Please login by <new line>a Valid ID and Password", "Please login by <br>a Valid ID and Password"},
                {"Re Code existed!","Re Code existed!" },
                {"From the form: Data updated successfully!","From the form: Data updated successfully!" },
                {"From the form: Data updated fail!","From the form: Data updated fail!" },
                {"All fields marked with an asterisk (<b style='color: Red; font-size: large'>*</b>) are required.","All fields marked with an asterisk (<b style='color: Red; font-size: large'>*</b>) are required." },
                {"From the form: Data inserted successfully!", "From the form: Data inserted successfully !"},
                {"Geocode is exites","Geocode is exites" },
                {"Error in process load database !!!","Error in process load database !!!"},
                {"Acc Type Code existed!","Acc Type Code existed!" },
                {"All fields marked with an asterisk (<b style='color: Red; font-size: large'>*</b>)are required.","All fields marked with an asterisk (<b style='color: Red; font-size: large'>*</b>)are required." },
                {"The RE field is required!","The RE field is required!" },
                {"The Sub RE field is required!","The Sub RE field is required!" },
                {"From the form: Error in process load database !!!","From the form: Error in process load database !!!" },
                {"Transfer successfull!","Transfer successfull!" },
                {"All fields marked with an asterisk (*) are required!","All fields marked with an asterisk (*) are required!" },
                {"Distributor Code existed!","Distributor Code existed!" },
                {"The CDS Code existed.","The CDS Code existed." },
                {"No Sales selected.","No Sales selected." },
                {"Have changed sucessfully.","Have changed sucessfully." },
                {"Program Code existed!","Program Code existed!" },
                {"The start date must be greater than current date!","The start date must be greater than current date!" },
                {"End date cannot less than start date!","End date cannot less than start date!" },
                {"End date cannot be less than current date!","End date cannot be less than current date!" },
                {"Program Code existed.","Program Code existed." },
                {"Stop Program successed !.","Stop Program successed !." },
                {"Remove photo sucessfull!","Remove photo sucessfull!" },
                {"RSM Code existed!","RSM Code existed!" },
                {"The ASM code exists.","The ASM code exists." },
                {"Geocode invalid!","Geocode invalid!" },
                {"Customer Code existed.","Customer Code existed." },
                {"Insert sucessfully!","Insert sucessfully!" },
                {"Update fail. Pls try again!","Update fail. Pls try again!" },
                {"From the from: data updated successfully!.","From the from: data updated successfully!." },
                {"Reset Geocode Success!","Reset Geocode Success!" },
                {"Reset Geocode Fail!","Reset Geocode Fail!" },
                {"Route Code existed.","Route Code existed." },
                {"Contest Code","Contest Code"},
                {"Contest Description","Contest Description"},
                {"Contest code existed.","Contest code existed."},
                {"MSS Contest Code","MSS Contest Code"},
                {"MSS Contest Description","MSS Contest Description"},
                {"The MSS Contest Code field is required!","The MSS Contest Code field is required!"},
                {"The MSS Contest Description field is required!","The MSS Contest Description field is required!"},
                {"Product not in contest","Product not in contest"},
                {"RE not in contest","RE not in contest"},


                //validate
                {"The program code field is required!","The program code field is required!" },
                {"The Acc Type Code field is required!","The Acc Type Code field is required!" },
                {"The Acc Type Description field is required!","The Acc Type Description field is required!" },
                {"The MSS Group Code field is required!","The MSS Group Code field is required!" },
                {"The MSS Group Description field is required!","The MSS Group Description field is required!" },
                {"The Min piece field is required!","The Min piece field is required!" },
                {"The RE Code field is required!","The RE Code field is required!" },
                {"The RE Description field is required!","The RE Description field is required!" },
                {"The Product Code field is required!","The Product Code field is required!" },
                {"The Product Name field is required!","The Product Name field is required!" },
                {"The Customer Code field is required!","The Customer Code field is required!" },
                {"The Customer Name field is required!","The Customer Name field is required!" },
                {"The Customer Type field is required!","The Customer Type field is required!"},
                {"The Distributor field is required!","The Distributor field is required!" },
                {"The DSR field is required!","The DSR field is required!" },
                {"The ASM Code field is required!","The ASM Code field is required!" },
                {"The ASM field is required!","The ASM field is required!" },
                {"The RSM field is required!","The RSM field is required!" },
                {"The RSM Code field is required!","The RSM Code field is required!" },
                {"The RSM Name field is required!","The RSM Name field is required!" },
                { "The Distributor Code field is required!","The Distributor Code field is required!"},
                { "The Distributor Name field is required!","The Distributor Name field is required!"},
                { "The Ward field is required!","The Ward field is required!"},
                { "The Geocode field is required!","The Geocode field is required!"},
                { "The Address field is required!","The Address field is required!"},
                { "Distributor Code","Distributor Code"},
                { "Distributor Name","Distributor Name"},
                {"All fields marked with an asterisk are required","All fields marked with an asterisk are required" },
                {"The CDS Name field is required!","The CDS Name field is required!" },
                {"The CDS Code field is required!","The CDS Code field is required!" },
                {"The program name field is required!","The program name field is required!" },
                {"The Route field is required!","The Route field is required!" },
                {"Please enter value between 0-60.","Please enter value between 0-60." },
                {"The distributor field is required","The distributor field is required" },
                {"The route field is required!","The route field is required!" },
                {"The MSSGroup Type field is reuiqred!","The MSSGroup Type field is reuiqred!" },
                {"The RE field is reuiqred!","The RE field is reuiqred!" },
                {"The SubRE field is reuiqred!","The SubRE field is reuiqred!" },
                {"The MSS DFG Group field is required!","The MSS DFG Group field is required!" },
                {"The Salesman List field is required!","The Salesman List field is required!" },
                {"The Product field is requierd!","The Product field is requierd!"},

                //Các header của gridview
                {"Acc Type Code","Acc Type Code" },
                {"Acc Type Description","Acc Type Description" },
                {"No.","No." },
                {"MSS Group Code","MSS Group Code" },
                {"MSS Group Description","MSS Group Description" },
                {"Min Piece","Min Piece" },
                {"Combo type","Combo type" },
                {"Special SKU","Special SKU" },
                {"Group Code","Group Code" },
                {"Group Description","Group Description" },
                {"Add Product","Add Product" },
                {"Add Acc Type","Add Acc Type" },
                {"Add RE","Add RE" },
                {"RE","RE" },
                {"RE not in group","RE not in group" },
                {"Remove RE","Remove RE" },
                {"RE Code","RE Code" },
                {"RE Description","RE Description" },
                {"Route Code","Route Code" },
                {"Route Name","Route Name" },
                {"Secondary Sale Perfomance - MTD - Current month (Mil)","Secondary Sale Perfomance - MTD - Current month (Mil)" },
                {"Primary Sale Perfomance - MTD - TH","Primary Sale Perfomance - MTD - Current Month" },
                {"DSRs - Sales","DSRs - Sales" },
                {"CDSs - Supervisor","CDSs - Supervisor" },
                {"DSRs","DSRs" },
                {"Add Distributor","Add Distributor" },
                {"Program Code","Program Code" },
                {"Program Name","Program Name" },
                {"Program of","Program of" },

                {"Start Date","Start Date" },
                {"End Date","End Date" },
                //Các label của textbox
                {"Active","Active" },
                {"F1 - 1*Monthly","F1 - 1*Monthly" },
                {"F2 - 2*Monthly","F2 - 2*Monthly" },
                {"F4 - 1*Weekly","F4 - 1*Weekly" },
                {"F8 - 2*Weekly","F8 - 2*Weekly" },
                {"F12 - 3*Weekly","F12 - 3*Weekly" },
                {"F24 - Daily","F24 - Daily" },
                {"Weekly visits","Weekly visits" },
                {"Week 1","Week 1" },
                {"Week 2","Week 2" },
                {"Week 3","Week 3" },
                {"Week 4","Week 4" },
                {"Mon","Mon" },
                {"Tue","Tue" },
                {"Web","Web" },
                {"Thu","Thu" },
                {"Fri","Fri" },
                {"Sat","Sat" },
                {"Sun","Sun" },
                {"Group Type Code","Group Type Code" },
                {"Group Type Description","Group Type Description" },

                {"Sub RE","Sub RE" },
                {"Start_Date","Start_Date" },
                {"End_Date","End_Date" },
                {"Distribution percent","Distribution percent" },
                {"From the form: Data inserted fail!","From the form: Data inserted fail!" },
                {"Special","Special" },
                {"Combo","Combo" },
                {"Route","Route" },
                {"Cust Code","Cust Code" },
                {"Cust Name","Cust Name" },
                {"Type","Type" },
                {"ASM Code","ASM Code" },
                {"ASM Name","ASM Name" },
                {"RSM","RSM" },
                {"Add Route","Add Route" },
                {"RSM Name","RSM Name" },
                {"RSM Code","RSM Code" },
                {"Month","Month" },
                {"%Growth 2019 vs 2018","%Growth 2019 vs 2018" },
                {"YTD","YTD" },
                {"SubCatg","SubCatg" },

                {"Date","Date"},
                {"From","From" },
                {"To","To"},
                {"Acc type not in group","Acc type not in group" },
                {"Remove Acc Type","Remove Acc Type" },
                {"Are you sure?","Are you sure?" },
                {"Acc Type","Acc Type" },
                {"Product not in group","Product not in group" },
                {"Remove product","Remove product" },
                {"Product Code","Product Code" },
                {"Product Name","Product Name" },

                {"List of children","List of children" },


                {"Infomation","Infomation" },

                {"Clear Filter","Remove all filters" },
                {"YTD Sales Perfomance - YTD (Mil)","YTD Sales Perfomance - YTD (Mil)" },
                {"YTD Primary Sales Perfomance - YTD (Mil)","YTD Primary Sales Perfomance - YTD (Mil)" },
                {"By","By" },
                {"DSRs - NVBH","DSRs - NVBH" },
                {"CDSs - Giám sát" ,"CDSs - Giám sát"},
                {"ASMs - Quản lý khu vực","ASMs - Quản lý khu vực" },
                {"DSR - NVBH","DSR - NVBH" },
                {"ASM","ASM" },
                {"Display","Display" },
                {"slow","slow" },
                {"fast","fast" },

                {"Go to page","Go to page" },

                {"Working date - Routes","Working date - Routes" },
                {"Visited but not sold","Visited but not sold" },
                {"Not visited but sold"  , "Not visited but sold"},
                {"Visited and sold","Visited and sold " },
                {"Not visited and not sold","Not visited and not sold" },
                {"No of stores in Routes","No of stores in Routes" },
                {"Actual visited in period","Actual visited in period" },
                {"% Visited to total","% Visited to total" },


                {"Frequency of visits","Frequency of visits" },
                {"Daily visit","Daily visit" },

                {"Add Customer","Add Customer" },
                {"Frequency","Frequency" },
                {"Customer Code","Customer Code" },

                {"Customer Name","Customer Name" },
                {"Customer Type","Customer Type" },
                {"District","District" },
                {"ECC","ECC" },
                {"Target","Target" },
                {"Visited","Visited" },
                {"Time Gone","Time Gone" },
                {"CDS","CDS" },
                {"MTD","MTD" },
                {"Area","Area"},
                { "Distributor","Distributor"},
                { "DSR","DSR"},
                { "Province","Province"},

                { "Address","Address"},
                {"Under Distributor","Under Distributor" },
                {"Region","Region" },
                {"Ward","Ward" },
                {"Geocode","Geocode" },
                {"CDS Code","CDS Code" },
                {"CDS Name","CDS Name" },
                {"Active/Deactive 5P Tracking","Active/Deactive 5P Tracking!" },

                {"Stop","Stop" },
                {"Apply for user","Apply for user" },
                {"Level Approve","Level Approve" },
                {"From date","From date" },
                {"To date","To date" },
                {"Program","Program" },
                {"Hide","Hide" },
                {"Customer","Customer" },
                {"Delete photo","Delete photo" },
                {"Info 1","Info 1" },
                {"Info 2","Info 2" },
                {"Info 3","Info 3" },
                {"Info 4","Info 4" },
                {"Info 5","Info 5" },
                {"AMS","AMS" },
                {"Channel","Channel" },
                {"No. of photo","No. of photo" },
                {"Reviewing approve","Reviewing approve" },
                {"Photo attached","Photo attached" },
                {"Duration","Duration" },
                {"Minute","Minute" },
                {"Seconds","Seconds" },
                {"Parent RE Code","Parent RE Code" },
                {"Parent RE Description","Parent RE Description" },
                {"Add Sub RE","Add Sub RE" },

                {"Sub Customer Type","Sub Customer Type" },
                {"MonthAgo","Number of previous months:" }, 

                //CÁc nút của báo cáo
                {"Export","Export" },
                {"List of sub RE","List of sub RE" },
                {"Sub RE Code","Sub RE Code" },
                {"Sub RE Description","Sub RE Description" },
                {"Export Template Import","Export Template Import" },

                {"End date must be after start date!","End date must be after start date!" },
                {"No data.","No data."},

                {"Time Period","Time Period" },
                {"MSS DFG Group","MSS DFG Group" },
                {"Salesman List","Salesman List" },
                {"Show/hide salesman","Show/hide salesman" },
                {"Primary Invoice Sale Perfomance - YTD (Mil)","Primary Invoice Sale Perfomance - YTD (Mil)" },
                {"Primary Sale Perfomance - MTD - Current month (Mil)","Primary Sale Perfomance - MTD - Current month (Mil)" },
                {"Note : when upload system will not update ward/commune if this information is empty.","Note : when upload system will not update ward/commune if this information is empty." },
                {"Upload MSS","Upload MSS" },
                {"Product code dupplicate","Product code dupplicate" },//messagesbox
                {"Product name dupplicate","Product name dupplicate" },//messagesbox
                {"Incorrect Date format error","Incorrect Date format error" },
                {"Extension of file is not valid!","Extension of file is not valid!" },
                {"File uploads don't exported from system.","File uploads don't exported from system." },
                {"CDM","CDM"},
                {"Missing Data","Missing Data" },
                {"Upload Products","Upload Products" },
                {"Upload list of customer","Upload list of customer" },
                {"Upload Sales Target Primary","Upload Sales Target Primary" },
                {"Upload Salaries","Upload Salaries" },
                {"Full Name","Full Name" },
                {"User Code","User Code"},
                {"User Name","User Name" },
                {"Confirm password","Confirm password"},
                {"Position","Position" },
                {"IsActivated","IsActivated" },
                {"Distributor assign","Distributor assign" },
                {"RSMs - Quản lí vùng","RSMs - Quản lí vùng"},

                //Dashboard
                {"ACH","ACH" },
                {"Year","Year" },
                {"Quarter","Quarter" },
                {"Store visited compliance","Store visited compliance" },
                {"Delete","Delete" },
            #endregion


            #region languages duplicate of Menu and Report Form
                
                {"Group Type","Group Type"},
                {"Brand","Brand" },
                {"Product","Product" },
                {"Working Itinerary","Working Itinerary" },
                {"Visualizing Coverage on Map","Visualizing Coverage on Map" },
                {"Setting and Reports","Setting and Reports" },
                {"5P Tracking","5P Tracking" },
                {"MSS Group","MSS Group" },

            #endregion

            #region setup language
                { "CurrencyUnit","Mđ"},
            #endregion






    };

    };

}
