USE [MMC_CPTH]
GO

/****** Object:  Table [dbo].[D_YTD_SALES_DATA_PRI_NEW]    Script Date: 10/10/2020 11:00:18 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[D_YTD_SALES_DATA_PRI_NEW](
	[CD_YTD_SALES_DATA_PRI_NEW] [bigint] IDENTITY(1,1) NOT NULL,
	[REGION] [nvarchar](255) NULL,
	[AREA] [nvarchar](255) NULL,
	[DIST] [nvarchar](50) NULL,
	[NAME] [nvarchar](255) NULL,
	[MONTH] [nvarchar](10) NULL,
	[YEAR] [nvarchar](4) NULL,
	[SUB_CATG] [nvarchar](50) NULL,
	[BRAND] [nvarchar](50) NULL,
	[GROSS_SALES_MLI] [float] NULL,
	[ACTIVE] [bit] NULL,
	[CREATED_DATE] [datetime] NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[D_YTD_SALES_DATA_PRI_NEW] ADD  CONSTRAINT [DF_D_YTD_SALES_DATA_PRI_NEW_ACTIVE_1]  DEFAULT ((1)) FOR [ACTIVE]
GO

ALTER TABLE [dbo].[D_YTD_SALES_DATA_PRI_NEW] ADD  CONSTRAINT [DF_D_YTD_SALES_DATA_PRI_NEW_CREATED_DATE_1]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO


