USE [MMC_CPTH]
GO

/****** Object:  Table [dbo].[TMP_IMPORT_SALES_TARGET]    Script Date: 16/09/2020 3:08:01 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TMP_IMPORT_SALES_TARGET_PRI](
	[TMP_CD] [bigint] IDENTITY(1,1) NOT NULL,
	[IMPORT_SALES_TARGET_PRI_CD] [nvarchar](100) NOT NULL,
	[DISTRIBUTOR_CODE] [nvarchar](50) NULL,
	[DISTRIBUTOR_CD] [bigint] NULL,
	[MONTH] [int] NULL,
	[YEAR] [int] NULL,
	[SALES_TARGET_YYYYMM] [int] NULL,
	[TOTAL_SALES_TARGET] [money] NULL,
	[TP_SALES_TARGET] [money] NULL,
	[TB_SALES_TARGET] [money] NULL,
	[CREATED_DATE] [datetime] NULL,
 CONSTRAINT [PK_TMP_IMPORT_SALES_TARGET_PRI] PRIMARY KEY CLUSTERED 
(
	[TMP_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TMP_IMPORT_SALES_TARGET_PRI] ADD  CONSTRAINT [DF_TMP_IMPORT_SALES_TARGET_PRI_TOTAL_SALES_TARGET]  DEFAULT ((0)) FOR [TOTAL_SALES_TARGET]
GO

ALTER TABLE [dbo].[TMP_IMPORT_SALES_TARGET_PRI] ADD  CONSTRAINT [DF_TMP_IMPORT_SALES_TARGET_PRI_TP_SALES_TARGET]  DEFAULT ((0)) FOR [TP_SALES_TARGET]
GO

ALTER TABLE [dbo].[TMP_IMPORT_SALES_TARGET_PRI] ADD  CONSTRAINT [DF_TMP_IMPORT_SALES_TARGET_PRI_TB_SALES_TARGET]  DEFAULT ((0)) FOR [TB_SALES_TARGET]
GO

ALTER TABLE [dbo].[TMP_IMPORT_SALES_TARGET_PRI] ADD  CONSTRAINT [DF_TMP_IMPORT_SALES_TARGET_PRI_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO


